### ISSUE TITLE
Villager interactions broken?

### ISSUE THREAD

**Issue by boomydude** [Tanguygab/RealVillagerTowns#1]
The plugin appears to load OK.  However, when I try to right click a villager, I don't get any interaction.  If I stop the server, remove your 1.7.1 jar, and put the original 1.6 jar from spigotmc.org in its place, then restart the server, the interactions works as expected.  This was tested on a new Spigot 1.20.1 server.

**Comment by Tanguygab** [comment]
I'll check tomorrow morning

**Comment by Tanguygab** [comment]
it appears that the plugin is completely broken after all, I guess I have more work on my hands 😿

**Comment by Tanguygab** [comment]
After 4 days of rearranging the code again, I have finally come up with a jar.
[RVT-2.0.0.zip](https://github.com/Tanguygab/RealVillagerTowns/files/11905022/RVT-2.0.0.zip)
Let me know if you encounter any errors

nvm, it's still broken

**Comment by Tanguygab** [comment]
Should be better
[RealVillagerTowns-2.0.0.zip](https://github.com/Tanguygab/RealVillagerTowns/files/11926759/RealVillagerTowns-2.0.0.zip)

**Comment by boomydude** [comment]
Thanks so much.  I like how the config files are better organized.  However, there is still some quirkiness with interactions.  Sometimes when I right click it goes right to trading, other times it the interaction menu comes up like it should, but when I try to trade (by right clicking again), it fails to do so.  I would like to be able to choose to interact or trade like the old 1.6 used to.  Thanks for your contributions.

**Comment by Tanguygab** [comment]
uh, weird, when I tried it, I wasn't even able to interact at all xD
I'll try to investigate further

**Comment by Tanguygab** [comment]
This was so stupid, idk why it took me a week to figure this out, but trading should be fixed now.
[RealVillagerTowns-2.0.0.zip](https://github.com/Tanguygab/RealVillagerTowns/files/11994936/RealVillagerTowns-2.0.0.zip)
btw instead of having to click the villager twice, you can just click on the Trade button and it'll open the trade menu

also, there seems to be an issue where villager skins keep changing, idk why this happens, I'll try my best ;-;

**Comment by boomydude** [comment]
It seems that I'm still having issues trading with some villagers.  The "trade" button just doesn't appear sometimes, even on a non-nitwit villager.

**Comment by Tanguygab** [comment]
if it doesn't appear, then that means that the villager doesn't have a profession (since 1.14 they need a specific block to get a profession, such as lecterns for librarians etc..)

**Comment by boomydude** [comment]
Thanks so much.  I haven't had a lot of time to test it yet, but it appears to work OK.
Jo

**Comment by boomydude** [comment]
Ok, thanks.  Any chance of releasing/publishing the version with your fixes
so far?  Or are you working on several other minor bugs, like skins
refreshing way too often, and the career label isn't updated when you right
click on a villager who has changed careers.  Should I open these as new
issues?

Thanks so much,
Jo

**Comment by Tanguygab** [comment]
villager professions are managed by minecraft directly, I just get the value so there should be nothing to update🤷 
but yeah, I'm still trying to fix this issue with skins
